apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv04
spec:
  capacity:
    storage: 10Gi 
  accessModes:
  - ReadWriteMany 
  nfs:
    server: 192.168.122.100 
    path: /var/nfs-data/pv04
  persistentVolumeReclaimPolicy: Recycle  
